### ISSUE TITLE
Unable to initialize a reader on iPhone 6

### ISSUE THREAD

**Issue by ulyandmi** [CardFlight/cardflight-ios#19]
The application that we developed using your API works well on iPhone 4 to iPhone 5s, but when we try to run it on iPhone 6, readerIsConnected returns an Error "Connecting to CardFlight timed out. Please try again". When I put a breakpoint in readerIsConnecting or readerIsAttached, stop application on the breakpoint and then resume it, it successfully connects.

**Comment by hokiewalrus** [comment]
Version 1.9.1 addresses this issue
