### ISSUE TITLE
CFTCard no longer NSCoding compliant

### ISSUE THREAD

**Issue by lennonhead** [CardFlight/cardflight-ios#20]
NSCoder needs to be added back to the CFTCard, used to work.

2   CoreFoundation                    0x182b85664 -[NSObject(NSObject) doesNotRecognizeSelector:] + 220
3   CoreFoundation                    0x182b82418 ___forwarding___ + 928
4   CoreFoundation                    0x182a86b6c _CF_forwarding_prep_0 + 92
5   Foundation                        0x1839cd430 _encodeObject + 1244
6   Foundation                        0x1839d4a4c +[NSKeyedArchiver archivedDataWithRootObject:] + 192

**Comment by hokiewalrus** [comment]
This will be added back into the next release

**Comment by hokiewalrus** [comment]
Added back into 1.9.2
