### ISSUE TITLE
CFTReader.h missing declaration for - (void)cancelSwipe

### ISSUE THREAD

**Issue by scottrhoyt** [CardFlight/cardflight-ios#22]
In the documentation for the now deprecated `- (void)cancelSwipeWithMessage:(NSString *)message` it calls for a switch to the `- (void)cancelSwipe` method.  The .h doesn't include a declaration for this.

**Comment by hokiewalrus** [comment]
Documentation was updated in 2.0.2 to reflect using `cancelTransaction` instead of `cancelSwipe`
