### ISSUE TITLE
Crash using RamblerReader 

### ISSUE THREAD

**Issue by appmagnetics** [CardFlight/cardflight-ios#23]
Hi, we have got this reported over Crashlytics:

Thread : Crashed: com.apple.main-thread
0  Control                        0x000db112 -[ReaderController stopSignalGen] + 13929
1  Control                        0x000da94b -[ReaderController getReaderKsn] + 11938
2  Control                        0x000da94b -[ReaderController getReaderKsn] + 11938
3  Control                        0x000be827 -[CFTRamblerReader checkForAttach] (CFTRamblerReader.mm:49)
4  Control                        0x000bbc23 -[CFTReader readerFailed:] (CFTReader.m:271)
5  Control                        0x000bcd31 -[CFTReader walkerConnected:] (CFTReader.m:457)
6  Control                        0x000cfd5f -[CFTWalkerReader onDeviceHere:] (CFTWalkerReader.mm:280)
7  Foundation                     0x2c0d7439 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 8
8  Foundation                     0x2c0420a1 -[NSBlockOperation main] + 148
9  Foundation                     0x2c034b0d -[__NSOperationInternal _start:] + 768
10 Foundation                     0x2c0d9d93 __NSOQSchedule_f + 186
11 libdispatch.dylib              0x39c96c6f _dispatch_client_callout + 22
12 libdispatch.dylib              0x39ca2553 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1322
13 CoreFoundation                 0x2b374889 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
14 CoreFoundation                 0x2b372fa9 __CFRunLoopRun + 1512
15 CoreFoundation                 0x2b2be9a1 CFRunLoopRunSpecific + 476
16 CoreFoundation                 0x2b2be7b3 CFRunLoopRunInMode + 106
17 GraphicsServices               0x32a6e1a9 GSEventRunModal + 136
18 UIKit                          0x2ea49695 UIApplicationMain + 1440
19 Control                        0x00057837 main (main.m:13)

**Comment by hokiewalrus** [comment]
Can you try upgrading to 2.0.4 and see if that solves your issue?
