### ISSUE TITLE
Support for AudioJack & Attache reader in the same app

### ISSUE THREAD

**Issue by amayers** [CardFlight/cardflight-ios#24]
You can't include both the AudioJack & Attache subspec in the same project. So there is no way to support both Lightning readers, and the new EMV reader without forcing all users of the app to switch to a new reader all at the same time which isn't really practical to do.

When you include both subspecs in the same target you get a ton of `duplicate symbol _OBJC_IVAR_$_CFTCardZip._zip in:` errors for basically every class in the library.

**Comment by hokiewalrus** [comment]
At this time we have no plans to support an environment of mixed audio jack and attache readers.
