### ISSUE TITLE
Card expiration month and year

### ISSUE THREAD

**Issue by citrus** [CardFlight/cardflight-ios#25]
It seems that you've reversed the expiration date for a CFTCard. My test card expires January 2018. When I successfully swipe, I get the following values:

```
expirationMonth: 18,
expirationYear: 01
```

Thoughts?

**Comment by ggamecrazy** [comment]
Confirmed, I have the same issue.

**Comment by hokiewalrus** [comment]
A new version of the SDK will be out shortly and it addresses this issue.

**Comment by hokiewalrus** [comment]
Version 3.0 (just released) should address this issue.
