### ISSUE TITLE
Incompatible with Xcode v7 (iOS 9)

### ISSUE THREAD

**Issue by jackrr** [CardFlight/cardflight-ios#27]
Building a project that includes CardFlight gives the following error:

`libCardFlightLibrary.a(CFTReader.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by hokiewalrus** [comment]
Version 3.0 (just released) is compatible with bitcode.

**Comment by robrichard** [comment]
I'm getting this error with 3.2.1

**Comment by hokiewalrus** [comment]
Apologies, there was an update and I did not update the issue.

Bitcode is currently not possible with libraries that need to run through lipo for creating a fat binary of mixed architectures. This is a bitcode limitation and not a CardFlight limitation. We are currently working on a solution

**Comment by hokiewalrus** [comment]
We currently have no workaround for this limo limitation and don't foresee any appearing in the near future.
