### ISSUE TITLE
Unable to cleanly generate dSYM

### ISSUE THREAD

**Issue by zachsnow** [CardFlight/cardflight-ios#29]
As of 3.0 I'm unable to cleanly generate a dSYM during build. The first relevant warnings:

```
while processing .../Pods/CardFlight/libCardFlightLibrary.a(CFTReader.o):
(null): warning: /var/folders/zx/6pf5dvzx73ncft9r72q5l8bh0000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/7.1-7B91b/Xcode/SharedPrecompiledHeaders/CardFlightLibrary-Prefix-crkcimwsrlabkmfiruhhczgfaxou/CardFlightLibrary-Prefix.pch.pch: No such file or directory
(null): warning: /var/folders/zx/6pf5dvzx73ncft9r72q5l8bh0000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/7.1-7B91b/Xcode/SharedPrecompiledHeaders/CardFlightLibrary-Prefix-crkcimwsrlabkmfiruhhczgfaxou/CardFlightLibrary-Prefix.pch.pch: No object file for requested architecture
```

Note the `.pch.pch` file extension above. Following that there are dozens of warnings like the examples below:

```
(null): warning: Could not resolve external type c:objc(cs)NSObject
(null): warning: Could not resolve external type c:objc(cs)NSDecimalNumber
(null): warning: Could not resolve external type c:objc(cs)NSString
```

**Comment by hokiewalrus** [comment]
We haven't seen that warning before. Can you clean your build folders and delete derived data and try compiling again?

**Comment by brblakley** [comment]
I've been seeing these same warnings. I just tried to reproduce it in a new dummy project and wasn't able to until changing 'Debug Information Format' from 'DWARF' to 'DWARF with dSYM file'.

Steps to reproduce:

1. Open Xcode 7.1.1.
2. Choose File > New > Project > iOS > Application > Single View Application (Language: Objective-C; Devices: iPhone; no checkboxes selected).
3. Close project.
4. `pod init`
5. Open Podfile and add `pod 'CardFlight'` to target.
6. `pod install`
7. Open workspace.
8. In the project's Build Settings > Enable Bitcode: No.
9. Select 'Generic iOS Device'.
10. Choose Product > Archive.

Look in the build's output for all the warnings.

(By default, the project's 'Debug Information Format' is 'DWARF' for Debug and 'DWARF with dSYM file' for Release.)

**Comment by zachsnow** [comment]
What @brblakley describes has been precisely my experience.

**Comment by hokiewalrus** [comment]
Interesting. I followed the steps outlined by @brblakley exactly, and I was not able to reproduce the warnings:

<img width="970" alt="screen shot 2015-11-24 at 2 04 37 pm" src="https://cloud.githubusercontent.com/assets/728021/11377596/a69f4424-92b4-11e5-8821-37177944377f.png">

Additionally, I changed the Debug info to DWARF with dSYM and and was still unable to generate the warnings.

There seem to be a lot of people with similar issues surrounding static libraries and broken dSYM, however it will be difficult to debug until I can reproduce. I will continue investigating.

**Comment by brblakley** [comment]
@hokiewalrus, thanks for looking into this. I'm not sure why we're getting different results. I ran through the steps again and the warnings show up for me. Here is the Xcode project/workspace with pods that I just used:

http://cl.ly/3D3S2T1f292Q/Demo.zip

Can you try running Product > Archive with that and see what you get?

**Comment by hokiewalrus** [comment]
Ah-ha! I have discovered the issue.

Xcode 7 added new CLANG module support, which must not be used on libraries that are going to be used on other computers. The reason I wasn't seeing the error was my machine has the paths being looked for.

We are prepping an update that fixes the error, it will be out soon.

**Comment by brblakley** [comment]
@hokiewalrus, any news on the release with the fix? Thanks.

**Comment by hokiewalrus** [comment]
Nothing concrete yet, we don't anticipate the next release being too much longer though

**Comment by Quentiu** [comment]
@hokiewalrus I'm seeing the same problem here, any news on when the next CardFlight release will be?

**Comment by hokiewalrus** [comment]
CardFlight 3.1 has been release and it should fix this issue
