### ISSUE TITLE
How to Read Unencrypted non Credit Card Data?

### ISSUE THREAD

**Issue by cebertowicz** [CardFlight/cardflight-ios#30]
In addition to processing credit cards for our POS system which is using Cardflight, we need to support reading membership cards of our customers.

We tried implementing method `readerGenericResponse` but it never gets called.
The CFTCard data which is returned in `readerCardResponse` method contains cardtype=UNKOWN and not the full membership number, which we need.

How can we read custom cards with CardFlight?

**Comment by benmarten** [comment]
+1

**Comment by hokiewalrus** [comment]
The CardFlight SDK no longer supports non ISO 7813 encoded magnetic stripe cards. readerGenericResponse was deprecated some time ago and has since been removed from the SDK, and we currently don't have any plans to add that functionality back in.
