### ISSUE TITLE
Invalid credentials when using Test mode and Test Token

### ISSUE THREAD

**Issue by invoodoo** [CardFlight/cardflight-ios#31]
This issue appears only when I'm using test mode, if in production everything is good.

2016-01-14 11:19:37.858 RacePay[4002:1081629] CardFlight __52-[CFTCard chargeCardWithParameters:success:failure:]_block_invoke{
    message = "Invalid credentials";
    options = "<null>";
    status = 500;
    type = "Cardflight::ApiError";
}
Charge Error: Error Domain=CardFlight Code=500 "Invalid credentials" UserInfo={NSLocalizedDescription=Invalid credentials}

**Comment by eltoob** [comment]
Usually you get this error if your account token and your api key are not matching.

If you are swtiching between test and production ... please make sure to change BOTH your account token and your api key

**Comment by applebyte1992** [comment]
I am also facing this same issue after double checking the Test and production environment keys, the problems still there.
