### ISSUE TITLE
“Card removed” error on disconnecting reader

### ISSUE THREAD

**Issue by brblakley** [CardFlight/cardflight-ios#32]
Steps to reproduce (using CardFlight iOS SDK 3.1):

- Call `[[CFTSessionManager sharedInstance] setLogging:YES]`.
- Call `-[CFTSessionManager setApiToken:accountToken:]` with an EMV-compatible account’s tokens.
- Connect an EMV-compatible reader.
- In `-[CFTReaderDelegate readerIsConnected:withError:]`, call `-[CFTReader beginEMVTransactionWithAmount:andChargeDictionary:]`.
- Disconnect the reader.

Expected result: `-[CFTReaderDelegate emvTransactionResult:requiresSignature:withError:]` called with no error or an error about the reader being disconnected.

Actual result: `-[CFTReaderDelegate emvTransactionResult:requiresSignature:withError:]` called with an error about a card being removed: `Error Domain=CardFlight Code=400 "Card removed" UserInfo={NSLocalizedDescription=Card removed}`

**Comment by hokiewalrus** [comment]
Fixed in version 3.2
