### ISSUE TITLE
EMV features unavailable when beginning EMV transaction before private asynchronous token process has finished

### ISSUE THREAD

**Issue by brblakley** [CardFlight/cardflight-ios#34]
Steps to reproduce (using CardFlight iOS SDK 3.1):

- Call `[[CFTSessionManager sharedInstance] setLogging:YES]`.
- Connect an EMV-compatible reader.
- Call `-[CFTSessionManager setApiToken:accountToken:]` with an EMV-compatible account’s tokens.
- In `-[CFTReaderDelegate readerIsConnected:withError:]`, call `-[CFTReader beginEMVTransactionWithAmount:andChargeDictionary:]`.

Expected result: `-[CFTReaderDelegate emvMessage:]` called with `EMVMessage_DIP_OR_SWIPE`.

Actual result: `-[CFTReaderDelegate emvMessage:]` called with `EMVMessage_USE_MAG_READER`.

Note that there appears to be a race condition. That is, if the `beginEMVTransactionWithAmount:andChargeDictionary:` call happens before the console shows `EMV ready:Yes`, the above unexpected behavior will occur. But if the call happens after that is logged, it will instead have the above expected behavior.

If there is some private asynchronous behavior that the caller must wait on, it would be helpful to have some kind of callback to notify the caller that the internal asynchronous routine is finished and it is now ready for transactions to begin.

**Comment by hokiewalrus** [comment]
Fixed in version 3.2
