### ISSUE TITLE
Stripe Integration Question

### ISSUE THREAD

**Issue by dltlr** [CardFlight/cardflight-ios#49]
I need some clarity on Stripe integration, maybe I haven't found the correct documentation.

If I have a card flight account setup and Stripe set as the merchant account.  Can I tokenize cards using CardFlight API "tokenizeCardWithSuccess" and be able to pass that card token later to Stripe directly to charge the swiped card? Or do I have to charge thru CardFlight api?

**Comment by hokiewalrus** [comment]
Once you have a token from stripe via the `tokenizeCardWithSuccess` method you then use that token directly on Stripe later to make charges
