### ISSUE TITLE
Swift: Value of type CFTCard has no member chargeCardWithParameters

### ISSUE THREAD

**Issue by sanketfirodiya** [CardFlight/cardflight-ios#52]
Other instance methods such as `tokenizeCardWithSuccess` are picked up by the compiler correctly.

<img width="937" alt="screen shot 2016-05-19 at 12 24 40 am" src="https://cloud.githubusercontent.com/assets/1585037/15385729/4aaba250-1d58-11e6-9b07-563bbd0f902f.png">

Using release 3.2

**Comment by Isuru-Nanayakkara** [comment]
Did you add the SDK via CocoaPods?

**Comment by sanketfirodiya** [comment]
No, I have added it manually.





On Wed, Jun 8, 2016 at 11:47 PM -0700, "Isuru Nanayakkara" <notifications@github.com> wrote:












Did you add the SDK via CocoaPods?

**Comment by hokiewalrus** [comment]
We currently have no official swift support, but we are working on it

**Comment by hokiewalrus** [comment]
Our new SDK, version 4 includes enhanced swift support: https://github.com/CardFlight/cardflight-v4-ios
