### ISSUE TITLE
Two Step Authorization

### ISSUE THREAD

**Issue by applebyte1992** [CardFlight/cardflight-ios#60]
Hi 

I am just exploring the API for card flight and I have to make a two step authorization process so I'll look into the API.The API is very rich and provides a lot of functionality. I have found an authorize method in the API which is returning me the CFTCharge Object that contains the token. Know I would like to make a Payment using that token but I'll not find any method that will allow me to charge the card based on the Token. It would be awful that you can provide me a little help on this or provide me a way to modify the payment once I have authorised or paid the amount. Right now its providing me the feature of refunding but its actually modifying the existing amount.
Such workflows usually work in restaurants for the Tip amount and actual bill payments.

I also found a method in CFTCharge Interface 
+ (void)cashChargeWithParameters:(NSDictionary *)chargeDictionary
                         success:(void(^)(CFTCharge *charge))success
                         failure:(void(^)(NSError *error))failure;

This method is not taking any kind on Token so how can we use that and which card we are actually charging as in other methods of this class token would be the parameter to identify the card.

Please help me on this.

**Comment by hokiewalrus** [comment]
@applebyte1992 The method you are looking for is `+ (void)captureChargeWithToken:(NSString *)token andAmount:(NSDecimalNumber *)amount success:(void(^)(CFTCharge *charge))success failure:(void(^)(NSError *error))failure;`. It is located in the CFTCharge class
