### ISSUE TITLE
Getting error 483 (Swipe error)

### ISSUE THREAD

**Issue by sanketfirodiya** [CardFlight/cardflight-ios#61]
I have been struggling with this error at a very high rate (~50%).
Tried different combinations of readers, devices and credit cards but unable to identify an external cause of failure.

This is how I am using the SDK - 

I have a singleton instance of `CFTReader` 
```
class CardReader: CFTReader {
  static var sharedInstance = CardReader()
}
```

And this is what I do when the user is going to swipe their card
```
if self.reader.hasValidStateForSwipe() {
        self.reader.beginSwipe()
}

func hasValidStateForSwipe() -> Bool {
    return self.readerState() == .ReaderState_CONNECTED ||
      self.readerState() == .ReaderState_WAITING_FOR_SWIPE ||
      self.readerState() == .ReaderState_WAITING_FOR_DIP ||
      self.readerState() == .ReaderState_SWIPE_DETECTED
  } 

```

Please let me know if there is any more info I can provide to debug this.

**Comment by sanketfirodiya** [comment]
Also, I am getting `Invalid card used for testing` on a few cards that work fine with Square/other readers. Is there documentation on the error codes?

**Comment by hokiewalrus** [comment]
@sanketfirodiya - First off I should say that we currently don't have official support for Swift, that is coming in a future release.

To your specific point, `ReaderState_SWIPE_DETECTED` is fired off after a card has been swiped, so if you are restarting the transaction by calling `beginSwipe` you will have issues.

Best practice is to wait until you receive the `- (void)readerIsConnected:(BOOL)isConnected withError:(NSError *)error` callback, and from that point forward you are cleared to begin listening for a swipe. If you are keying off the reader state, it is possible that you are restarting swipes often, which may or may not be causing some issues.

**Comment by sanketfirodiya** [comment]
@hokiewalrus thanks for the reply.

I didn't paste all the code, but yes I am waiting for `- (void)readerIsConnected:(BOOL)isConnected withError:(NSError *)error` to tell me when the reader is ready.

Then, when the user taps the `Pay` button in my app, I am calling -
```
if self.reader.hasValidStateForSwipe() {
        self.reader.beginSwipe()
}
```

I will change this to 
```
if self.reader.hasValidStateForSwipe() {
        if self.reader.readerState() != .ReaderState_SWIPE_DETECTED {
          self.reader.beginSwipe()
        }
        self.askUserToSwipeCardDialog()
}
```
so that I don't restart swipes.

There is another error I am facing on some specific cards though - `Invalid card used for testing`. These cards work fine when I use the Production API key on the SDK but throw this error when I switch to using the Test API key.
Any ideas what I am doing wrong?

**Comment by hokiewalrus** [comment]
@sanketfirodiya - That sounds like a Stripe error to me, it not an error that we generate. Every processor handles testing differently, so Stripe will accept/reject different cards than Square or someone else will.

Because Stripe deals primarily with non-swiped cards they have some very specific requirements when it comes to test cards, please see https://stripe.com/docs/testing#cards
