### ISSUE TITLE
Private API Usage of forceStop

### ISSUE THREAD

**Issue by jwilliams-handy** [CardFlight/cardflight-ios#63]
My app was just rejected from the App Store due to the use of private API usage. Through the use of "otool -ov" and the "strings" command I believe I have attributed the call back to your pod.

The offending private API call is `forceStop`. I believe it's called from the `PS_onReturnMagStripeCardNumber:` selector in the `EmvDeviceController` class but I'm not an "otool" expert so I'm not completely certain.

Can you affirm in your source if you are using this method and what would be the timeline for remediation? We are unable to submit until this is patched.

**Comment by jwilliams-handy** [comment]
After clarification from Apple they have told us that `EmvDeviceController` is the culprit but it's being called from the selector `forceStopOtaController`.

**Comment by hokiewalrus** [comment]
False positive
