### ISSUE TITLE
CFTPaymentView modifying size

### ISSUE THREAD

**Issue by auctifera-josed** [CardFlight/cardflight-ios#65]
When initializing the CFTPaymentView object, I'm not seeing any change in the size regardless of the values (width, height) in the CGRect, is that the expected behavior? or how can I change the dimensions of the CFTPaymentView?

Note: The x, y location works like a charm.

**Comment by hokiewalrus** [comment]
This is functionality we are considering implementing in a future release. As of right now, this is expected behavior. The position of the view may be set but the size is currently fixed.
