### ISSUE TITLE
Bad response from server (Vaulting)

### ISSUE THREAD

**Issue by alijawadGGS** [CardFlight/cardflight-ios#68]
Hi
We are integrating the Vaulting functionlity in our system to save user card so that we'll save his effort of card insertion everytime. We have integrated your SDK and successfully charged the card using the proper API calls but when we tried to Vault the card using the same API Key and Access Token we are always getting Bad response from server. Below is the code that we are using to Vault the card. Please help us in that.
We are using your sample code for iOS. Please take a look into it as soon as possible as its affecting our business.

- (void)keyedCardResponse:(CFTCard *)card {
    if (card) {
        
        [card vaultCardWithSuccess:^{
            NSLog(@"%@",card.vaultID);
        } failure:^(NSError *error) {
            NSLog(@"%@",error.localizedDescription);
        }];
        self.manualCard = card;
        [self enableManualButtons:YES];
    }
}

**Comment by hokiewalrus** [comment]
Will handle privately via email as this isn't a systemic issue with the SDK
