### ISSUE TITLE
Charge Card - Stripe Connect

### ISSUE THREAD

**Issue by patmisch** [CardFlight/cardflight-ios#71]
When attempting to charge a swiped card via the ChargeCardWithParameters method, I'm getting the following error:

'Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided'

Given that, I tried to use the TokenizeCardWithSuccess method, but have had no success. This method returns 500 - Bad response from server.

**Comment by hokiewalrus** [comment]
Tokenization has now been fixed in CardFlight 3.6, which you can find at the new repo here:

https://github.com/CardFlight/cardflight-v3-ios
