### ISSUE TITLE
tokenizeCard returning error on newer readers

### ISSUE THREAD

**Issue by ashfurrow** [CardFlight/cardflight-ios#72]
Good afternoon! I'm having a problem with newer readers. Old ones work fine but when I try to use the new ones and call `tokenizeCard` on `CFTCard`, I'm getting back `Error Domain=CardFlight Code=500 "Bad response from server" UserInfo={NSLocalizedDescription=Bad response from server}`. Any ideas what could be causing this?

**Comment by ashfurrow** [comment]
Any update on this? We're using 3.5.1 of the library.

**Comment by hokiewalrus** [comment]
This issue is a known bug and will be fixed in the next release.

**Comment by ashfurrow** [comment]
For anyone else experiencing this issue, rolling back to 3.2.1 of the SDK fixed it for now.
